language: node_js
node_js:
  - "4"
sudo: required
before_install:
  - npm install
  - npm run tsd-install
  - npm run build
install:
  - sudo npm install . -g --unsafe --production
script:
  - npm test
after_script:
  - sudo npm uninstall . -g --unsafe
notifications:
  email: false