version: "3.7"
services:
  mahiron:
    build:
      context: .
    image: 21S1298001/mahiron:latest
    container_name: mahiron
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      DOCKER_NETWORK: host
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    network_mode: host
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - type: bind
        source: /opt/mahiron/run/
        target: /var/run/
      - type: bind
        source: /opt/mahiron/opt/
        target: /opt/
      - type: bind
        source: /opt/mahiron/config/
        target: /app-config/
      - type: bind
        source: /opt/mahiron/data/
        target: /app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
