version: "3.7"
networks:
  default:
    name: mirakurun
services:
  mirakurun:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: chinachu/mirakurun:latest
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    ports:
      - 40772:40772
      # - 9229:9229
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      # ** CAUTION **
      # (default) `/usr/local/mirakurun/*` has been moved to `/opt/mirakurun/*`
      # try:
      #   sudo mv -vf /usr/local/mirakurun /opt/mirakurun
      #   sudo mkdir -p /opt/mirakurun/run /opt/mirakurun/opt /opt/mirakurun/config /opt/mirakurun/data
      # you can change to any location if required.
      - type: bind
        source: /opt/mirakurun/run/
        target: /var/run/
      - type: bind
        source: /opt/mirakurun/opt/
        target: /opt/
      - type: bind
        source: /opt/mirakurun/config/
        target: /app-config/
      - type: bind
        source: /opt/mirakurun/data/
        target: /app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
