devices:
  - name: PT3-S1
    types:
      - BS
      - CS
    command: recpt1 --device /dev/pt3video0 --lnb 15 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT3-S2
    types:
      - BS
      - CS
    command: recpt1 --device /dev/pt3video1 --lnb 15 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT3-T1
    types:
      - GR
    command: recpt1 --device /dev/pt3video2 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT3-T2
    types:
      - GR
    command: recpt1 --device /dev/pt3video3 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT2-S1
    types:
      - BS
      - CS
    group: PT2
    command: recpt1 --device /dev/pt1video0 --lnb 15 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT2-S2
    types:
      - BS
      - CS
    group: PT2
    command: recpt1 --device /dev/pt1video1 --lnb 15 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT2-T1
    types:
      - GR
    group: PT2
    command: recpt1 --device /dev/pt1video2 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: PT2-T2
    types:
      - GR
    group: PT2
    command: recpt1 --device /dev/pt1video3 <channel> - -
    decoder: b25 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

  - name: TBS6922
    types:
      - SKY
    group: dvb-s2
    dvbTuneCommand: szap-s2j -c /usr/local/etc/szap-s2j.conf -l <satelite> -S 1 -p -r -M 5 -C 35 -ch <channel>
    dvbDevicePath: /dev/dvb/adapter0/dvr0
    decoder: b1 -v 0 -s 1 /dev/stdin /dev/stdout
    isDisabled: true

group:
  PT2:
    controlWait: 3000