- name: PT3-S1
  types:
    - BS
    - CS
  command: BonRecTest.exe --driver BonDriver_PT3-S.dll --output - --channel <channel>
  decoder: ~
  isDisabled: true

- name: PT3-S2
  types:
    - BS
    - CS
  command: BonRecTest.exe --driver BonDriver_PT3-S.dll --output - --channel <channel>
  decoder: ~
  isDisabled: true

- name: PT3-T1
  types:
    - GR
  command: BonRecTest.exe --driver BonDriver_PT3-T.dll --output - --channel <channel>
  decoder: ~
  isDisabled: true

- name: PT3-T2
  types:
    - GR
  command: BonRecTest.exe --driver BonDriver_PT3-T.dll --output - --channel <channel>
  decoder: ~
  isDisabled: true