name: ci

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Check by linters
        run: pnpm run lint

      - name: Check server by tsc
        run: pnpm run type-check:server

      - name: Build server
        run: pnpm run build

      - name: Check ui by tsc
        run: pnpm run type-check:ui

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Build server
        run: pnpm run build

      - name: Run test
        run: pnpm run test
